CREATE TABLE challenge_t(
  challenge_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
  challenge_text VARCHAR(1024),
  CONSTRAINT challenge_pk PRIMARY KEY (challenge_id)
);

CREATE TABLE checkpoint_t(
  checkpoint_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  challenge BIGINT,
  CONSTRAINT checkpoint_pk PRIMARY KEY (checkpoint_id),
  CONSTRAINT challenge_fk FOREIGN KEY (challenge)
  REFERENCES challenge_t (challenge_id)
);

CREATE TABLE player_t(
  player_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
  first_name VARCHAR(64) NOT NULL,
  last_name VARCHAR(64) NOT NULL,
  student_number CHAR(9) NOT NULL,
  password CHAR(32) NOT NULL,
  administrator BOOLEAN,
  CONSTRAINT player_pk PRIMARY KEY (player_id),
  CONSTRAINT player_sid UNIQUE (student_number)
);

CREATE TABLE team_t(
  team_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
  players VARCHAR(10),
  CONSTRAINT team_pk PRIMARY KEY (team_id)
);

CREATE TABLE path_t(
  path_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
  checkpoints VARCHAR(64),
  CONSTRAINT path_pk PRIMARY KEY (path_id)
);

CREATE TABLE scavengerhunt_t(
  scavenger_hunt_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
  path BIGINT NOT NULL,
  completed_checkpoints VARCHAR(64),
  team BIGINT NOT NULL,
  start_time TIMESTAMP,
  finish_time TIMESTAMP,
  CONSTRAINT scavengerhunt_pk PRIMARY KEY (scavenger_hunt_id),
  CONSTRAINT scavengerhunt_path_fk FOREIGN KEY (path)
  REFERENCES path_t (path_id),
  CONSTRAINT scavengerhunt_team_fk FOREIGN KEY (team)
  REFERENCES team_t (team_id)
);

----------------------------------------------------------------------------------------------------

-- The hashes here are just the password '123456' MD5 hashed
-- Admin password is "admin"
INSERT INTO
        player_t(first_name, last_name, student_number, password, administrator)
        VALUES ('The', 'Administrator', '999999999',
                '21232F297A57A5A743894A0E4A801FC3', TRUE),
                ('Jason', 'Recillo', '100123123',
                        'E10ADC3949BA59ABBE56E057F20F883E', FALSE),
                ('Peter', 'Le', '100145965',
                        'E10ADC3949BA59ABBE56E057F20F883E', FALSE),
                ('Mellicent', 'Dres', '100793317',
                        'E10ADC3949BA59ABBE56E057F20F883E', FALSE),
                ('Lincoln', 'Earlls', '100158465',
                        'E10ADC3949BA59ABBE56E057F20F883E', FALSE),
                ('James', 'Mackin', '100456415',
                        'E10ADC3949BA59ABBE56E057F20F883E', FALSE);

INSERT INTO team_t(players) VALUES ('2,3'), ('1,4');

INSERT INTO challenge_t (challenge_text)
        VALUES ('First go there and do this thing.'),
                ('Go here and there.'),
                ('Do this thing at this place.');

INSERT INTO
        checkpoint_t(latitude, longitude, challenge)
        VALUES (43.675854, -79.71069, 0),
                (43.676130, -79.410492, 1),
                (43.6754555, -79.410492, 2);

INSERT INTO path_t (checkpoints) VALUES ('0,1,2'), ('0,2,1');

INSERT INTO
        scavengerhunt_t (path, team, start_time, finish_time)
        VALUES (0, 0,
                TIMESTAMP('2012-11-27 10:00:00'),
                TIMESTAMP('2012-11-27 16:00:00'));

INSERT INTO
        scavengerhunt_t(path, team, start_time, finish_time, completed_checkpoints)
        VALUES (1, 1,
                TIMESTAMP('2012-11-27 10:00:00'),
                TIMESTAMP('2012-11-27 16:00:00'),
                '0');
