CREATE TABLE checkpoint(
	checkpoint_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
	latitude REAL NOT NULL,
	longitude REAL NOT NULL,
	challenge INT
);

CREATE TABLE player(
	player_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
	first_name varchar(64) NOT NULL,
	last_name varchar(64) NOT NULL,
	student_number char(9) NOT NULL
);

CREATE TABLE team(
	team_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
	players VARCHAR(10)
);

CREATE TABLE scavengerhunt(
	scavenger_hunt_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
	path INT NOT NULL,
	team INT NOT NULL,
	start_time TIMESTAMP,
	finish_time TIMESTAMP
);

CREATE TABLE path(
	path_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
	checkpoints VARCHAR(64)
);

CREATE TABLE challenge(
	challenge_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
	challenge_text VARCHAR(1024)
);

INSERT INTO player(first_name, last_name, student_number) VALUES
	('Jason', 'Recillo', '100726948'),
	('Peter', 'Le', '100714258'),
	('Mellicent', 'Dres', '100726767');

INSERT INTO team(players) VALUES
	('1,2');

INSERT INTO checkpoint(latitude, longitude, challenge) VALUES
	(43.675854, -79.71069, NULL);
