CREATE TABLE challenge_t(
  challenge_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
  challenge_text VARCHAR(1024),
  CONSTRAINT challenge_pk PRIMARY KEY (challenge_id)
);

CREATE TABLE checkpoint_t(
  checkpoint_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  challenge BIGINT,
  CONSTRAINT checkpoint_pk PRIMARY KEY (checkpoint_id),
  CONSTRAINT challenge_fk FOREIGN KEY (challenge)
  REFERENCES challenge_t (challenge_id)
);

CREATE TABLE player_t(
  player_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
  first_name varchar(64) NOT NULL,
  last_name varchar(64) NOT NULL,
  student_number char(9) NOT NULL,
  CONSTRAINT player_pk PRIMARY KEY (player_id),
  CONSTRAINT player_sid UNIQUE (student_number)
);

CREATE TABLE team_t(
  team_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
  players VARCHAR(10),
  CONSTRAINT team_pk PRIMARY KEY (team_id)
);

CREATE TABLE path_t(
  path_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
  checkpoints VARCHAR(64),
  CONSTRAINT path_pk PRIMARY KEY (path_id)
);

CREATE TABLE scavengerhunt_t(
  scavenger_hunt_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1),
  path BIGINT NOT NULL,
  team BIGINT NOT NULL,
  start_time TIMESTAMP,
  finish_time TIMESTAMP,
  CONSTRAINT scavengerhunt_pk PRIMARY KEY (scavenger_hunt_id),
  CONSTRAINT scavengerhunt_path_fk FOREIGN KEY (path)
  REFERENCES path_t (path_id),
  CONSTRAINT scavengerhunt_team_fk FOREIGN KEY (team)
  REFERENCES team_t (team_id)
);

----------------------------------------------------------------------------------------------------

INSERT INTO
    player_t(first_name, last_name, student_number)
    VALUES ('Jason', 'Recillo', '100123123'),
        ('Peter', 'Le', '100145965'),
        ('Mellicent', 'Dres', '100793317'),
        ('Lincoln', 'Earlls', '100158465'),
        ('James', 'Mackin', '100456415');

INSERT INTO team_t(players) VALUES ('1,2'), ('0,3');

INSERT INTO challenge_t (challenge_text)
    VALUES ('First go there and do this thing.'),
        ('Go here and there.'),
        ('Do this thing at this place.');

INSERT INTO
    checkpoint_t(latitude, longitude, challenge)
    VALUES (43.675854, -79.71069, 0),
        (43.676130, -79.410492, 1),
        (43.6754555, -79.410492, 2);

INSERT INTO path_t (checkpoints) VALUES ('0,1'), ('0,2');

INSERT INTO
    scavengerhunt_t (path,team,start_time,finish_time)
    VALUES (0, 0,
        TIMESTAMP('2012-11-27 10:00:00'),
        TIMESTAMP('2012-11-27 16:00:00')),
        (1, 1,
            TIMESTAMP('2012-11-27 10:00:00'),
            TIMESTAMP('2012-11-27 16:00:00'));
